"""fix tables

Revision ID: 02aa9ad6b427
Revises: 93b191555921
Create Date: 2023-07-06 14:35:44.332392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aa9ad6b427'
down_revision = '93b191555921'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_inn', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_inn'), 'companies', ['company_inn'], unique=True)
    op.create_table('sallers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saller_name', sa.String(), nullable=True),
    sa.Column('saller_inn', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sallers_saller_inn'), 'sallers', ['saller_inn'], unique=True)
    op.create_foreign_key(None, 'leasing_contracts', 'sallers', ['saller_id'], ['id'])
    op.create_foreign_key(None, 'leasing_contracts', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leasing_contracts', type_='foreignkey')
    op.drop_constraint(None, 'leasing_contracts', type_='foreignkey')
    op.drop_index(op.f('ix_sallers_saller_inn'), table_name='sallers')
    op.drop_table('sallers')
    op.drop_index(op.f('ix_companies_company_inn'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
