"""Fixing current state of the database

Revision ID: 1d487c035b3c
Revises: 
Create Date: 2024-02-20 13:09:54.862061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d487c035b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_contracts', 'floating_or_not')
    op.drop_index('idx_leasing_receiver_inn', table_name='dima_base')
    op.create_index(op.f('ix_dima_base_supplier_inn'), 'dima_base', ['supplier_inn'], unique=False)
    op.create_foreign_key(None, 'interest_rate_history', 'payments', ['payment_id'], ['id'])
    op.create_foreign_key(None, 'leasing_contracts', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'leasing_contracts', 'sellers', ['seller_id'], ['id'])
    op.create_foreign_key(None, 'payment_schedules', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_schedules', type_='foreignkey')
    op.drop_constraint(None, 'leasing_contracts', type_='foreignkey')
    op.drop_constraint(None, 'leasing_contracts', type_='foreignkey')
    op.drop_constraint(None, 'interest_rate_history', type_='foreignkey')
    op.drop_index(op.f('ix_dima_base_supplier_inn'), table_name='dima_base')
    op.create_index('idx_leasing_receiver_inn', 'dima_base', ['leasing_receiver_inn'], unique=False)
    op.add_column('credit_contracts', sa.Column('floating_or_not', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
