"""added indexes and UserMixin

Revision ID: 8926f36068a9
Revises: 1a33aaded0e4
Create Date: 2023-07-01 13:21:31.845688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8926f36068a9'
down_revision = '1a33aaded0e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_banks_bank_name'), 'banks', ['bank_name'], unique=False)
    op.drop_constraint('leasing_contracts_leasing_contract_number_key', 'leasing_contracts', type_='unique')
    op.create_index(op.f('ix_leasing_contracts_leasing_contract_number'), 'leasing_contracts', ['leasing_contract_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leasing_contracts_leasing_contract_number'), table_name='leasing_contracts')
    op.create_unique_constraint('leasing_contracts_leasing_contract_number_key', 'leasing_contracts', ['leasing_contract_number'])
    op.drop_index(op.f('ix_banks_bank_name'), table_name='banks')
    # ### end Alembic commands ###
