"""added table sallers

Revision ID: 93b191555921
Revises: 114525841582
Create Date: 2023-07-06 12:07:59.018407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b191555921'
down_revision = '114525841582'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sallers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saller_name', sa.String(), nullable=True),
    sa.Column('saller_inn', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sallers_saller_inn'), 'sallers', ['saller_inn'], unique=True)
    op.add_column('leasing_contracts', sa.Column('saller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leasing_contracts', 'sallers', ['saller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leasing_contracts', type_='foreignkey')
    op.drop_column('leasing_contracts', 'saller_id')
    op.drop_index(op.f('ix_sallers_saller_inn'), table_name='sallers')
    op.drop_table('sallers')
    # ### end Alembic commands ###
