"""Added new model PercentPaymentDate

Revision ID: f364ce431241
Revises: 1d487c035b3c
Create Date: 2024-03-12 12:36:15.684028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f364ce431241'
down_revision = '1d487c035b3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('percents_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_contract_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['credit_contract_id'], ['credit_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('percents_dates')
    # ### end Alembic commands ###
